export const GETTERS = {
  ARTICLES: 'ARTICLES/ARTICLES'
};

export const MUTATIONS = {
  SET_ARTICLES: 'ARTICLES/SET_ARTICLES',
  ADD: 'ARTICLES/ADD'
  // UPDATE_CURRENT: 'ARTICLES/UPDATE_CURRENT'
};

export const ACTIONS = {
  GET_ALL: 'ARTICLES/GET_ALL',
  ADD: 'ARTICLES/ADD'
  // UPDATE: 'ARTICLES/UPDATE',
  // REMOVE: 'ARTICLES/REMOVE'
};

export default {
  GETTERS,
  MUTATIONS,
  ACTIONS
};
