export const GETTERS = {
  ARTICLES: 'ARTICLES/ARTICLES'
};

export const MUTATIONS = {
  SET_ARTICLES: 'ARTICLES/SET_ARTICLES',
  ADD: 'ARTICLES/ADD',
  UPDATE: 'ARTICLES/UPDATE',
  REMOVE: 'ARTICLES/REMOVE'
};

export const ACTIONS = {
  GET_ALL: 'ARTICLES/GET_ALL',
  GET_BY_ID: 'ARTICLES/GET_BY_ID',
  ADD: 'ARTICLES/ADD',
  UPDATE: 'ARTICLES/UPDATE',
  REMOVE: 'ARTICLES/REMOVE'
};

export default {
  GETTERS,
  MUTATIONS,
  ACTIONS
};
