export const GETTERS = {
  SHOW_MODAL: 'AUTH/SHOW_MODAL',
  TOKENS: 'AUTH/TOKENS'
};

export const MUTATIONS = {
  TOGGLE_MODAL: 'AUTH/TOGGLE_MODAL',
  SET_TOKENS: 'AUTH/SET_TOKENS'
};

export const ACTIONS = {
  REGISTER: 'AUTH/REGISTER',
  LOGIN: 'AUTH/LOGIN'
};

export default {
  GETTERS,
  MUTATIONS,
  ACTIONS
};
